[package]
name = "brain-dump-app"
version = "0.1.0"
edition = "2024"

[lib]
name = "brain_dump_app_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-shell = "2"
brain-dump-core = { path = "../brain-dump-core" }
rusqlite = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
